name: Manual Release Android

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Setup Java
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # 3. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.7"
          channel: "stable"
          cache: true

      # 4. Dependencies
      - run: flutter pub get

      # 5. 🔍 Ambil version dari pubspec
      - name: Get version
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //g' | cut -d '+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 6. 🔐 Inject keystore
      - name: Decode keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../app/upload-keystore.jks" >> android/key.properties

      # 7. Build
      - run: flutter build apk --release

      # 8. 🧾 Generate changelog (optional)
      - name: Generate changelog
        id: changelog
        run: |
          LOG=$(git log -10 --pretty=format:"- %s")
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$LOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 9. 🚀 Create Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          body: |
            ## 🚀 Changes
            ${{ steps.changelog.outputs.changelog }}
          files: |
            build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
